# Reference: https://github.com/google/accompanist/blob/main/.github/workflows/build.yml
name: Build & test

on:
  push:
    branches:
      - main
      - github-actions
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  setup:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
      - uses: actions/checkout@v2
        #with:
          # Fetch expanded history, which is needed for affected module detection
          #fetch-depth: '500'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11


  build-file-sharing-producer:
    needs: setup

    steps:
      - name: Build file-sharing-producer
      run: |
        cd file-sharing-producer
        ./gradlew --scan --stacktrace \
            assemble \
            lintDebug


  build-file-sharing-consumer:
    needs: setup

    steps:
      - name: Build file-sharing-consumer
      run: |
        cd file-sharing-consumer
        ./gradlew --scan --stacktrace \
            assemble \
            lintDebug


  upload-artifacts:
    needs: setup
    
    steps:
       - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/build/test-results/*
            **/build/reports/*