# Reference: https://github.com/google/accompanist/blob/main/.github/workflows/build.yml
name: Build & test

on:
  push:
    branches:
      - main
      - github-actions
      - renovate/**
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        project: ["file-sharing-producer", "file-sharing-consumer", "vision-qr-code-scanner"]

    steps:
      - uses: actions/checkout@v2
        #with:
          # Fetch expanded history, which is needed for affected module detection
          #fetch-depth: '500'

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build
        env:
          PROJECT_DIR: ${{ matrix.project }}
        run: |
          cd $PROJECT_DIR
          ./gradlew --scan --stacktrace \
              assemble \
              lintDebug
        

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            **/build/test-results/*
            **/build/reports/*
